### ISSUE TITLE
Few design issues

### ISSUE THREAD

**Issue by yanone** [docrepair-fonts/belanosima-fonts#1]
There are a few glyphs which really go beyond the pleasant, in my opinion. The Ø and ø in the Bold belong to them, and certainly the @ in all weights. It reaches over both sidebearings.

Ultimately, the decision is yours. I would at least try find a solution for the @.

<img width="515" alt="Bildschirm­foto 2023-04-04 um 10 05 20" src="https://user-images.githubusercontent.com/175386/229728401-e3ea3087-7c02-49d4-a9ae-92728295b878.png">
<img width="286" alt="Bildschirm­foto 2023-04-04 um 10 07 01" src="https://user-images.githubusercontent.com/175386/229728678-6eb1234d-a48e-4181-85db-5b54b62e2678.png">

**Comment by twardoch** [comment]
I'll fix it

**Comment by twardoch** [comment]
I’ve improved the design of `at` and `Oslash`. I’ve also changed `Semibold` to `SemiBold` in the master names and file names. I had to rebuild the entire font, so the DS+UFO has changed. 

<img width="914" alt="scr- 2023-04-04 at 12 03 05" src="https://user-images.githubusercontent.com/519108/229758571-5117d948-7b10-4de8-a4e7-b36824b96a85.png">

**Comment by twardoch** [comment]
I’ve made some more tweaks, and generally made some non-alphabetic glyphs in the Bold master lighter (they were suffering from extrapolation artefacts)

**Comment by yanone** [comment]
I already made all the naming changes, which are now lost again, but I'll repeat it. What's with the 700 weight class? It doesn't need to stay like this, does it?

**Comment by yanone** [comment]
I did it. Closing this.
